config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'orders/confirm', to: 'orders#confirm'
  get 'orders/complete', to: 'orders#complete'
  post 'orders/back', to: 'orders#back'

  resources :orders, only: %i[new create show back] do
    collection do
      post :confirm
    end
  end

  devise_for :users
  resources :users, only: %i[edit]
  post '/users/:id/update', to: 'users#update', as: 'update_user'
  get '/mypage' => 'users#show'
  get     'mypage/like', to: 'users#like'
  get     'mypage/review', to: 'users#review'
  get     'mypage/order_history', to: 'users#order_history'

  resources :shops, only: %i[show]
  get     'shops/login',   to: 'sessions#new'
  post    'shops/login',   to: 'sessions#create'
  delete  'shops/logout',  to: 'sessions#destroy'

  get '/carts', to: 'carts#show'
  post '/add_item', to: 'carts#add_item'
  post '/update_item', to: 'carts#update_item'
  delete '/delete_item', to: 'carts#delete_item'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :products do
    resources :reviews, only: %i[index create]
    post 'add', to: 'likes#create'
    delete '/add', to: 'likes#destroy'
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

include JpPrefecture
  jp_prefecture :prefecture_code

  validates :postcode, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_category_relations, dependent: :destroy
  has_many :products, through: :product_category_relations
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates_uniqueness_of :product_id, scope: :user_id
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  # belongs_to :product
  has_many :order_products, dependent: :destroy
  accepts_nested_attributes_for :order_products, allow_destroy: true
  include JpPrefecture
  jp_prefecture :prefecture_code

  validates :receipt_date, presence: true
  validates :receipt_time, presence: true
  validates :postcode, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
  belongs_to :shop
end

app/models/photo.rb
class Photo < ApplicationRecord
      mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  acts_as_taggable
  belongs_to :shop
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  has_many :order_products
  # has_many :product_category_relations, dependent: :destroy
  # has_many :category, through: :product_category_relations

  def avg_score
    if reviews.empty?
      0.0
    else
      reviews.average(:rate).round(1).to_f
    end
  end

  def review_score_percentage
    if reviews.empty?
      0.0
    else
      reviews.average(:rate).round(1).to_f * 100 / 5
    end
  end

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :image, presence: true
  validates :description, presence: true
  validates :quantity_per_day,
            presence: true,
            numericality: { only_integer: true }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :rate, presence: true
  validates :comment, presence: true

  def review_rate_percentage
    rate.to_f * 100 / 5
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :products, dependent: :destroy
  has_secure_password validations: true
  has_many :order_products, dependent: :destroy

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end

  validates :email, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_products, through: :likes, source: :product
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true

  validates :first_name, presence: true

  validates :last_hurigana,
            presence: true,
            format: {
              with: /\A[\p{katakana}\p{blank}ー－]+\z/,
              message: 'はカタカナで入力して下さい。'
            }

  validates :first_hurigana,
            presence: true,
            format: {
              with: /\A[\p{katakana}\p{blank}ー－]+\z/,
              message: 'はカタカナで入力して下さい。'
            }

  validates :password,
            presence: true,
            length: { minimum: 6 }

  validates :email,
            presence: true,
            uniqueness: true

  def already_liked?(product)
    likes.exists?(product_id: product.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[show like review order_history edit update]
  def show
    @user = User.find(current_user.id)
    @address = Address.find_by(user_id: current_user.id)
  end

  def edit
  end

  def update
    @address = Address.find_by(user_id: current_user.id)
    if @address.present?
      @address.user_id = current_user.id
      @address.update(address_params)
      flash[:notice] = '住所を登録しました。'
      redirect_to mypage_path
    else
      @address = Address.new(address_params)
      @address.user_id = current_user.id
      if @address.save
        flash[:notice] = '住所を変更しました。'
        redirect_to mypage_path
      else
        binding.pry
        #redirect_back fallback_location: @user., flash: {
        #review: @review,
        #error_messages: @review.errors.full_messages
      #}
      end
    end
  end

  def like
    @likes = Like.where(user_id: current_user.id)
  end

  def review
    @reviews = Review.where(user_id: current_user.id)
  end

  def order_history
    @orders = Order.where(user_id: current_user.id).order(id: 'DESC')
    @orders = @orders.page(params[:page]).per(5)
  end

  private
  def address_params
    params.permit(:postcode, :prefecture_code, :address_city, :address_street, :address_building)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_shop
    remember_token = Shop.encrypt(cookies[:shop_remember_token])
    @current_shop ||= Shop.find_by(remember_token: remember_token)
  end

  def sign_in(shop)
    remember_token = Shop.new_remember_token
    cookies.permanent[:shop_remember_token] = remember_token
    shop.update!(remember_token: Shop.encrypt(remember_token))
    @current_shop = shop
  end

  def sign_out
    @current_shop = nil
    cookies.delete(:shop_remember_token)
  end

  def signed_in?
    @current_shop.present?
  end

  private

  def require_sign_in!
    redirect_to shops_login_path unless signed_in?
  end
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_editForm.html.erb
  <%= render 'shared/error_messages' %>

<%= form_with url: update_user_path(current_user.id),local: true  do |f| %>
  <div class="form-group row">
    <label class="col-sm-3 col-form-label">郵便番号</label>
    <div class="col-sm-9">
      <%= f.text_field :postcode , id: "user_postcode", class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-3 col-form-label">都道府県</label>
    <div class="col-sm-9">
       <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name, { prompt: '選択してください' }, class: 'form-control', id: 'user_prefecture_code' %>  
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-3 col-form-label">市区町村</label>
    <div class="col-sm-9">
    <%= f.text_field :address_city , id: "user_address_city", class: 'form-control' %>   
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-3 col-form-label">番地</label>
    <div class="col-sm-9">
    <%= f.text_field :address_street , id: "user_address_street" , class: 'form-control'%>   
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-3 col-form-label">建物名</label>
    <div class="col-sm-9">
    <%= f.text_field :address_building , class: 'form-control' %>   
    </div>
  </div>
  <%= f.submit '変更', class: 'btn btn-primary' %>
  <% end %>

app/views/users/_form.html.erb
<%= render 'shared/error_messages' %>

<div class="card">
  <h5 class="card-header">ユーザー登録</h5>
  <div class="card-body d-flex align-items-center">
    
<%= form_for user do |f| %>
  <div class="form-row">
    <div class="col col-md-6">
    <%= f.label :last_name, '姓' %>
    <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="col col-md-6">
    <%= f.label :first_name, '名' %>
    <%= f.text_field :first_name, class: 'form-control' %>
    </div>
  </div>

    <div class="form-row">
    <div class="col col-md-6">
    <%= f.label :last_hurigana, 'セイ' %>
    <%= f.text_field :last_hurigana, class: 'form-control' %>
    </div>
    <div class="col col-md-6">
    <%= f.label :first_hurigana, 'メイ' %>
    <%= f.text_field :first_hurigana, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit '作成', class: 'btn btn-primary' %>
<% end %>

  </div>
</div>

app/views/users/_menu.html.erb
<div class="menu">
<ul class="nav nav-tabs menu">
  <li class="nav-item">
  <%= active_link_to 'お気に入り', mypage_like_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= active_link_to 'マイレビュー', mypage_review_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
  <%= active_link_to '購入履歴', mypage_order_history_path, class: 'nav-link' %>
  </li>
</ul>
</div>


    

app/views/users/edit.html.erb
<div class="center-block contents mt-4">
 <div class="card">
  <div class="card-header">
    <h3>住所変更</h3>
  </div>
   <%= render 'shared/error_messages' %>
  <div class="card-body m-4">
   <%= render partial: 'editForm' %>
  </div>
 </div>
</div>

app/views/users/like.html.erb
<div class=" mt-5">
<div class="card contents">
<div class="card-body"> 
<%= render partial: 'menu', locals: { user: @user } %>
    <div class="py-5">
    <% if @likes.present? %>
    <% @likes.each do |like| %>
      <% product = Product.find_by(id: like.product_id) %>
      <div class="card mb-3">
       <div class="row no-gutters">
        <div class="col-md-4">
        <%= image_tag product.image.url, :width => '100%', :height => '225', class: 'index-img' %>
       </div>
       <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= product.name %></h5>
        <p class="card-text"><%= product.description %></p>
        <h5 class="card-title">¥<%= product.price %></h5>
        <div class="text-right">
        <%= link_to  "商品ページへ", product, class: 'btn btn-outline-info w-10'%>
        </div>
      </div>
    </div>
  </div>
</div>
    <% end %>
    <% else %>
      <div class="card text-center">
       <div class="card-body">
        <h5 class="card-title">現在お気に入り登録している商品はありません</h5>
       </div>
      </div>
    <% end %>
    </div>
    </div>
    </div>
    </div>

app/views/users/login.html.erb
<h1>ログイン</h1>

<%= form_with scope: :session, url: login_path do |f| %>
  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <%= f.submit 'ログイン', class: 'btn btn-primary' %>
<% end %>

app/views/users/new.html.erb
<%= render partial: 'form', locals: { user: @user } %>
 

app/views/users/order_history.html.erb
  <div class=" mt-5">
<div class="card contents">
<div class="card-body"> 

  <%= render partial: 'menu', locals: { user: @user } %>
  <div class="py-5">
      <% if @orders.present? %>
      <% @orders.each do |order| %>
      <div class="card">
          <div class="card-header">
              <div class="row">
                  <div class="col-md-4">
                      ご注文日<br>
                      <%= order.created_at.strftime('%-m月 %-d日') %>
                  </div>
                  <div class="col-md-4">
                      配達日時<br>
                      <%= order.receipt_date.strftime('%-m月 %-d日') %>　　<%= time_format(order.receipt_time) %>
                  </div>
                  <div class="col-md-4">
                      合計金額<br>
                      ¥<%= order.total_price %>
                  </div>
              </div>
          </div>
          <% order_products = OrderProduct.where(order_id: order.id) %>
          <% order_products.each do |order_product| %>
          <% op = order_product.product %>
          <% shop = Shop.find_by(id: order_product.shop_id) %>
          <div class="card mb-3">
              <div class="row no-gutters">
                  <div class="col-md-4">
                      <%= image_tag op.image.url, :width => '100%', :height => '225', class: 'index-img' %>
                  </div>
                  <div class="col-md-8">
                      <div class="card-body">
                          <h5 class="card-title"><%= link_to  "#{op.name}", op, class: ''%></h5>
                          <h5 class="card-title">¥<%= op.price %></h5>
                          <h5 class="card-title"><%= link_to  "ショップ：#{shop.name}", shop_path(shop.id), class: ''%></h5>
                      </div>
                  </div>
              </div>
          </div>
          <% end %>
      </div>
      <% end %>
      <% else %>
      <div class="card text-center">
          <div class="card-body">
              <h5 class="card-title">現在お気に入り登録している商品はありません</h5>
          </div>
      </div>
      <% end %>
      <div class="mt-2">
      <%= paginate @orders %>
      </div>
  </div>
  </div>
  </div>
  </div>

app/views/users/review.html.erb
<div class=" mt-5">
<div class="card contents">
<div class="card-body"> 
  <%= render partial: 'menu', locals: { user: @user } %>
<div class="py-5">
     <% if @reviews.present? %>
    <% @reviews.each do |review| %>
      <% product = Product.find_by(id: review.product_id) %>
      <div class="card mb-3">
       <div class="row no-gutters">
        <div class="col-md-4">
        <%= image_tag product.image.url, :width => '100%', :height => '225', class: 'index-img' %>
       </div>
       <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= product.name %></h5>
        <h5 class="card-title ">
        <div class="star-rating mb-2" style="white-space: nowrap !important;">
            <div class="star-rating-front" style="width: <%= review.review_rate_percentage %>%">★★★★★</div>
            <div class="star-rating-back">★★★★★</div>
            </div>
        </h5>
         <div class="review-text" >
          <p class="card-text"><%= review.comment %></p>
         </div>
        <div class="text-right">
        <%= link_to  "商品ページへ", product, class: 'btn btn-outline-info w-10'%>
        </div>
      </div>
    </div>
  </div>
</div>
    <% end %>
    <% else %>
      <div class="card text-center">
       <div class="card-body">
        <h5 class="card-title">現在投稿したレビューはありません</h5>
       </div>
      </div>
    <% end %>
</div>
</div>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="mt-5">
  <div class="card contents">
    <div class="card-body contents">
        <%= render partial: 'menu', locals: { user: @user } %>
        <div class="py-5">
          <div class="card">
            <div class="card-header">
              <h4>プロフィール</h4>
            </div>
              <div class="card-body">
                <div class="form-group mb-4">
                    <label>お名前</label>
                    <div class="text-left">
                       <%= @user.last_name %> <%= @user.first_name %>様
                    </div>
                </div>
                <div class="form-group">
                  <label>お届け先住所</label>
                   <div class="text-left mb-2">
                     <% if @address.present? %>
                        〒<%= @address.postcode %><br>
                       <%= @address.prefecture_name %>
                       <%= @address.address_city %>
                       <%= @address.address_street %>
                       <%= @address.address_building %><br>
                       <% else %>
                       <p>現在住所は登録されていません</p>
                     <% end %>
                   </div>
                      <%= link_to '変更する', edit_user_path(current_user.id), class: 'edit-btn' %>
                </div>
                <hr>
                <div class="form-group">
                  <label>メールアドレス</label>
                  <div class="text-left">
                   <%= @user.email %><br>
                   <%= link_to '変更する',edit_user_registration_path  , class: 'edit-btn' %>
                  </div>
                </div>
                <br>
              </div> 
        </div>
      </div>
  </div>
</div>