config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'orders/confirm', to: 'orders#confirm'
  get 'orders/complete', to: 'orders#complete'
  post 'orders/back', to: 'orders#back'

  resources :orders, only: %i[new create show back] do
    collection do
      post :confirm
    end
  end

  devise_for :users
  resources :users, only: %i[edit]
  post '/users/:id/update', to: 'users#update', as: 'update_user'
  get '/mypage' => 'users#show'
  get     'mypage/like', to: 'users#like'
  get     'mypage/review', to: 'users#review'
  get     'mypage/order_history', to: 'users#order_history'

  resources :shops, only: %i[show]
  get     'shops/login',   to: 'sessions#new'
  post    'shops/login',   to: 'sessions#create'
  delete  'shops/logout',  to: 'sessions#destroy'

  get '/carts', to: 'carts#show'
  post '/add_item', to: 'carts#add_item'
  post '/update_item', to: 'carts#update_item'
  delete '/delete_item', to: 'carts#delete_item'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :products do
    resources :reviews, only: %i[index create]
    post 'add', to: 'likes#create'
    delete '/add', to: 'likes#destroy'
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

include JpPrefecture
  jp_prefecture :prefecture_code

  validates :postcode, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_category_relations, dependent: :destroy
  has_many :products, through: :product_category_relations
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates_uniqueness_of :product_id, scope: :user_id
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  # belongs_to :product
  has_many :order_products, dependent: :destroy
  accepts_nested_attributes_for :order_products, allow_destroy: true
  include JpPrefecture
  jp_prefecture :prefecture_code

  validates :receipt_date, presence: true
  validates :receipt_time, presence: true
  validates :postcode, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
  belongs_to :shop
end

app/models/photo.rb
class Photo < ApplicationRecord
      mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  acts_as_taggable
  belongs_to :shop
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  has_many :order_products
  # has_many :product_category_relations, dependent: :destroy
  # has_many :category, through: :product_category_relations

  def avg_score
    if reviews.empty?
      0.0
    else
      reviews.average(:rate).round(1).to_f
    end
  end

  def review_score_percentage
    if reviews.empty?
      0.0
    else
      reviews.average(:rate).round(1).to_f * 100 / 5
    end
  end

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :image, presence: true
  validates :description, presence: true
  validates :quantity_per_day,
            presence: true,
            numericality: { only_integer: true }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :rate, presence: true
  validates :comment, presence: true

  def review_rate_percentage
    rate.to_f * 100 / 5
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :products, dependent: :destroy
  has_secure_password validations: true
  has_many :order_products, dependent: :destroy

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end

  validates :email, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_products, through: :likes, source: :product
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true

  validates :first_name, presence: true

  validates :last_hurigana,
            presence: true,
            format: {
              with: /\A[\p{katakana}\p{blank}ー－]+\z/,
              message: 'はカタカナで入力して下さい。'
            }

  validates :first_hurigana,
            presence: true,
            format: {
              with: /\A[\p{katakana}\p{blank}ー－]+\z/,
              message: 'はカタカナで入力して下さい。'
            }

  validates :password,
            presence: true,
            length: { minimum: 6 }

  validates :email,
            presence: true,
            uniqueness: true

  def already_liked?(product)
    likes.exists?(product_id: product.id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :setup_cart_item, only: %i[add_item update_item delete_item]

  def show
    @cart_items = current_cart.cart_items
    @total_price = 0
    @cart_items.each do |cart_item|
      @total_price += cart_item.product.price.to_i * cart_item.quantity
    end
  end

  def add_item
    @cart_item = current_cart.cart_items.build(product_id: params[:product_id]) if @cart_item.blank?
    @cart_item.quantity += params[:quantity].to_i
    @cart_item.save
    flash[:notice] = 'カートに追加しました'
    redirect_back fallback_location: @cart_item.product
  end

  def update_item
    @cart_item.update(quantity: params[:quantity].to_i)
    redirect_back fallback_location: carts_path
  end

  def delete_item
    @cart_item.destroy
    redirect_back fallback_location: carts_path
  end

  private

  def setup_cart_item
    @cart_item = current_cart.cart_items.find_by(product_id: params[:product_id])
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_shop
    remember_token = Shop.encrypt(cookies[:shop_remember_token])
    @current_shop ||= Shop.find_by(remember_token: remember_token)
  end

  def sign_in(shop)
    remember_token = Shop.new_remember_token
    cookies.permanent[:shop_remember_token] = remember_token
    shop.update!(remember_token: Shop.encrypt(remember_token))
    @current_shop = shop
  end

  def sign_out
    @current_shop = nil
    cookies.delete(:shop_remember_token)
  end

  def signed_in?
    @current_shop.present?
  end

  private

  def require_sign_in!
    redirect_to shops_login_path unless signed_in?
  end
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_bill.html.erb
   <% cart_items.each do |cart_item| %>
     <div class="row no-gutters">
        <div class="col-md-3">
        <%= image_tag cart_item.product.image.url, :width => '100%', :height => '100%', class: 'show-img' %>
       </div>
       <div class="col-md-5">
        <div class="text-center">
          <h5><%= cart_item.product.name %></h5>
          <%= render partial: 'form', locals: {cart_item: cart_item } %>
         </div>
       </div>
       <div class="col-md-4 text-right">
        <h5 class="mr-4">¥<%= cart_item.product.price %></h5>
       </div>
      </div>
      <hr>
   <% end %>
  <div class="row">
      <div class="col-md-6 text-left">
       <h4>合計</h4>
      </div>
      <div class="col-md-6 text-right">
       <h4 class="mr-3">¥<%= @total_price %></h4>
      </div>
  </div>

app/views/carts/_form.html.erb
<%= form_with url: update_item_path, local: true do |f| %>
         <label class="my-1 mr-2" >個数</label>
          <%= f.select :quantity, {'1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '10': 10}, {selected: cart_item.quantity }, { class: 'custom-select my-1 mr-sm-2 select_tag'} %>
          <%= f.hidden_field :product_id, :value => cart_item.product.id %>
          <%= f.submit '更新', class: 'btn btn-primary my-1 mr-2' %>
          <%= link_to '削除', delete_item_path(product_id: cart_item.product.id), method: :delete %>
<% end %>

app/views/carts/show.html.erb
<div class="contents mt-4">
    <div class="card">
        <div class="card-body contents mt-4">
            <h4 class="card-title">ショッピングカート</h4>
            <% if @cart_items.present? %>
            <div class="text-right">
                <h5 class="mr-4">価格</h5>
            </div>
            <hr>
            <%= render partial: 'bill', locals: {cart_items: @cart_items } %>
            <div class="text-center mb-4">
            <%= link_to '注文する', new_order_path, class: 'btn btn-primary order-btn' %>
            </div>
            <% else %>
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">現在カートに商品はありません</h5>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>