config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'orders/confirm', to: 'orders#confirm'
  get 'orders/complete', to: 'orders#complete'
  post 'orders/back', to: 'orders#back'

  resources :orders, only: %i[new create show back] do
    collection do
      post :confirm
    end
  end

  devise_for :users
  resources :users, only: %i[edit]
  post '/users/:id/update', to: 'users#update', as: 'update_user'
  get '/mypage' => 'users#show'
  get     'mypage/like', to: 'users#like'
  get     'mypage/review', to: 'users#review'
  get     'mypage/order_history', to: 'users#order_history'

  resources :shops, only: %i[show]
  get     'shops/login',   to: 'sessions#new'
  post    'shops/login',   to: 'sessions#create'
  delete  'shops/logout',  to: 'sessions#destroy'

  get '/carts', to: 'carts#show'
  post '/add_item', to: 'carts#add_item'
  post '/update_item', to: 'carts#update_item'
  delete '/delete_item', to: 'carts#delete_item'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :products do
    resources :reviews, only: %i[index create]
    post 'add', to: 'likes#create'
    delete '/add', to: 'likes#destroy'
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

include JpPrefecture
  jp_prefecture :prefecture_code

  validates :postcode, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_category_relations, dependent: :destroy
  has_many :products, through: :product_category_relations
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates_uniqueness_of :product_id, scope: :user_id
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  # belongs_to :product
  has_many :order_products, dependent: :destroy
  accepts_nested_attributes_for :order_products, allow_destroy: true
  include JpPrefecture
  jp_prefecture :prefecture_code

  validates :receipt_date, presence: true
  validates :receipt_time, presence: true
  validates :postcode, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
  belongs_to :shop
end

app/models/photo.rb
class Photo < ApplicationRecord
      mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  acts_as_taggable
  belongs_to :shop
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  has_many :order_products
  # has_many :product_category_relations, dependent: :destroy
  # has_many :category, through: :product_category_relations

  def avg_score
    if reviews.empty?
      0.0
    else
      reviews.average(:rate).round(1).to_f
    end
  end

  def review_score_percentage
    if reviews.empty?
      0.0
    else
      reviews.average(:rate).round(1).to_f * 100 / 5
    end
  end

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :image, presence: true
  validates :description, presence: true
  validates :quantity_per_day,
            presence: true,
            numericality: { only_integer: true }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :rate, presence: true
  validates :comment, presence: true

  def review_rate_percentage
    rate.to_f * 100 / 5
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :products, dependent: :destroy
  has_secure_password validations: true
  has_many :order_products, dependent: :destroy

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end

  validates :email, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_products, through: :likes, source: :product
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true

  validates :first_name, presence: true

  validates :last_hurigana,
            presence: true,
            format: {
              with: /\A[\p{katakana}\p{blank}ー－]+\z/,
              message: 'はカタカナで入力して下さい。'
            }

  validates :first_hurigana,
            presence: true,
            format: {
              with: /\A[\p{katakana}\p{blank}ー－]+\z/,
              message: 'はカタカナで入力して下さい。'
            }

  validates :password,
            presence: true,
            length: { minimum: 6 }

  validates :email,
            presence: true,
            uniqueness: true

  def already_liked?(product)
    likes.exists?(product_id: product.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search
  helper_method :current_cart

  def current_cart
    Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
    cart
  end

  def set_search
    @search = Product.ransack(params[:q])
    @results = @search.result
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[last_name first_name last_hurigana first_hurigana])
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header_link_item(name, path)
    class_name = 'nav-item'
    class_name << ' active' if current_page?(path)

    content_tag :li, class: class_name do
      link_to name, path, class: 'nav-link'
    end
  end

  def time_format(int_time)
    case int_time
    when 1
      '10:00~12:00'
    when 2
      '13:00~15:00'
    when 3
      '15:00~17:00'
    when 4
      '17:00~19:00'
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_footer.html.erb
<footer class="text-muted py-5 bg-white mt-4">
<div class="contents">
    <p class="float-end mb-1">
      スイーツデリ
    </p>
    <p class="mb-1">COPYRIGHT &#169; スイーツデリ ALL RIGHTS RESERVED. </p>
    </div>
</footer>

app/views/application/_header.html.erb
    <header class="site-header">
        <div class="wrapper site-header__wrapper">
            <div class="site-header__start ml-4">
                <%= link_to 'スイーツデリ', root_path, class: 'brand text-nowrap' %>
            </div>
            <div class="search text-nowrap">
                <form class="form-inline search-box">
                    <%= search_form_for @search do |f| %>
                    <%= f.search_field :name_cont , class:'form-control mr-sm-2 search-input', placeholder: "商品名を入力" %>
                    <%= f.submit class: 'btn btn-outline-info w-10 my-2 my-sm-0' %>
                    <% end %>
                </form>
            </div>
            <div class="site-header__end">
                <nav class="nav">
                    <ul class="nav__wrapper mt-2 mb-2 mr-4">
                        <div class="nav__item text-center">
                            <%= link_to root_path do %>
                            <i class="fas fa-home"></i><br>
                            <span class="text-nowrap">ホーム</span>
                            <% end %>
                        </div>
                        <div class="nav__item text-center">
                            <%= link_to products_path do %>
                            <i class="fas fa-birthday-cake"></i><br>
                            <span class="text-nowrap">商品一覧</span>
                            <% end %>
                        </div>
                        <div class="nav__item text-center dropdown">
                            <a class="dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-user"></i><br>
                                <span class="text-nowrap">ユーザー</span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <% if user_signed_in? %>
                                <%= link_to 'マイページ', mypage_path, class: 'dropdown-item' %>
                                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                                <% else %>
                                <%= link_to '登録', new_user_registration_path, class: 'dropdown-item' %>
                                <%= link_to 'ログイン', new_user_session_path, class: 'dropdown-item' %>
                                <% end %>
                            </div>
                        </div>
                        <div class="nav__item text-center">
                            <%= link_to carts_path do %>
                            <i class="fas fa-shopping-cart"></i><br>
                            <span class="text-nowrap">カート</span>
                            <% end %>
                        </div>
                    </ul>
                </nav>
            </div>
        </div>
    </header>