config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'orders/confirm', to: 'orders#confirm'
  get 'orders/complete', to: 'orders#complete'
  post 'orders/back', to: 'orders#back'

  resources :orders, only: %i[new create show back] do
    collection do
      post :confirm
    end
  end

  devise_for :users
  resources :users, only: %i[edit]
  post '/users/:id/update', to: 'users#update', as: 'update_user'
  get '/mypage' => 'users#show'
  get     'mypage/like', to: 'users#like'
  get     'mypage/review', to: 'users#review'
  get     'mypage/order_history', to: 'users#order_history'

  resources :shops, only: %i[show]
  get     'shops/login',   to: 'sessions#new'
  post    'shops/login',   to: 'sessions#create'
  delete  'shops/logout',  to: 'sessions#destroy'

  get '/carts', to: 'carts#show'
  post '/add_item', to: 'carts#add_item'
  post '/update_item', to: 'carts#update_item'
  delete '/delete_item', to: 'carts#delete_item'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :products do
    resources :reviews, only: %i[index create]
    post 'add', to: 'likes#create'
    delete '/add', to: 'likes#destroy'
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

include JpPrefecture
  jp_prefecture :prefecture_code

  validates :postcode, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_category_relations, dependent: :destroy
  has_many :products, through: :product_category_relations
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates_uniqueness_of :product_id, scope: :user_id
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  # belongs_to :product
  has_many :order_products, dependent: :destroy
  accepts_nested_attributes_for :order_products, allow_destroy: true
  include JpPrefecture
  jp_prefecture :prefecture_code

  validates :receipt_date, presence: true
  validates :receipt_time, presence: true
  validates :postcode, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
  belongs_to :shop
end

app/models/photo.rb
class Photo < ApplicationRecord
      mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  acts_as_taggable
  belongs_to :shop
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  has_many :order_products
  # has_many :product_category_relations, dependent: :destroy
  # has_many :category, through: :product_category_relations

  def avg_score
    if reviews.empty?
      0.0
    else
      reviews.average(:rate).round(1).to_f
    end
  end

  def review_score_percentage
    if reviews.empty?
      0.0
    else
      reviews.average(:rate).round(1).to_f * 100 / 5
    end
  end

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :image, presence: true
  validates :description, presence: true
  validates :quantity_per_day,
            presence: true,
            numericality: { only_integer: true }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :rate, presence: true
  validates :comment, presence: true

  def review_rate_percentage
    rate.to_f * 100 / 5
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :products, dependent: :destroy
  has_secure_password validations: true
  has_many :order_products, dependent: :destroy

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end

  validates :email, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_products, through: :likes, source: :product
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true

  validates :first_name, presence: true

  validates :last_hurigana,
            presence: true,
            format: {
              with: /\A[\p{katakana}\p{blank}ー－]+\z/,
              message: 'はカタカナで入力して下さい。'
            }

  validates :first_hurigana,
            presence: true,
            format: {
              with: /\A[\p{katakana}\p{blank}ー－]+\z/,
              message: 'はカタカナで入力して下さい。'
            }

  validates :password,
            presence: true,
            length: { minimum: 6 }

  validates :email,
            presence: true,
            uniqueness: true

  def already_liked?(product)
    likes.exists?(product_id: product.id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_tags
  def index
    @product = Product.all
    if params[:tag_name]
      @tag_results = Product.tagged_with(params[:tag_name])
      @products = @tag_results.page(params[:page])
      #@products = @tag_results.paginate(page: params[:page], per_page: 15)
    else
      @products = @results.page(params[:page])
    end
  end

  def new
    @product = Product.new(flash[:product])
  end

  def create
    product = Product.new(product_params)
    if product.save
      flash[:notice] = "「#{product.name}」を作成しました"
      redirect_to product
    else
      redirect_back fallback_location: new_product_path, flash: {
        product: product,
        error_messages: product.errors.full_messages
      }
    end
  end

  def show
    @cart = Cart.new
    @product = Product.find(params[:id])
    @review = Review.new
    @reviews = @product.reviews.limit(5)
  end

  private

  def set_tags
    @tags = ActsAsTaggableOn::Tag.all
  end

  def product_params
    params.require(:product).permit(:name, :price, :image, :description, :shop_id, :quantity_per_day, :tag_list,
                                    tag_list: [])
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_shop
    remember_token = Shop.encrypt(cookies[:shop_remember_token])
    @current_shop ||= Shop.find_by(remember_token: remember_token)
  end

  def sign_in(shop)
    remember_token = Shop.new_remember_token
    cookies.permanent[:shop_remember_token] = remember_token
    shop.update!(remember_token: Shop.encrypt(remember_token))
    @current_shop = shop
  end

  def sign_out
    @current_shop = nil
    cookies.delete(:shop_remember_token)
  end

  def signed_in?
    @current_shop.present?
  end

  private

  def require_sign_in!
    redirect_to shops_login_path unless signed_in?
  end
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= render 'shared/error_messages' %>

<%= form_with model: product,local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, '商品名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price, '価格(税込み)' %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :quantity_per_day, '1日の提供数' %>
    <%= f.text_field :quantity_per_day, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image, '商品画像' %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, '商品説明' %>
    <%= f.text_area :description, class: 'form-control', rows: 10 %>
  </div>
<%= f.hidden_field :shop_id, value: 1 %>
   <div class="form-group">
    <span>カテゴリーを登録</span>
    <div class="card" style="width: 30rem; ">
     <div class="card-body">
    <% @tags.each do |tag| %>
          <span class="badge badge-light">
          <%= f.check_box :tag_list, { multiple: true }, "#{tag.name}", nil %>
          <%= f.label " #{tag.name}(#{tag.taggings_count})" %>
          </span>
        <% end %>
     </div>
    </div>    
</div>

  <%= f.submit '保存', class: 'btn btn-primary' %>
<% end %>

app/views/products/_productIndex.html.erb
<% products.each do |product| %>
<div class="col-md-4">
    <div class="card mb-4 shadow-sm" style="white-space: nowrap !important;">
        <div class="product-img">
            <% if product.image? %>
            <%= image_tag product.image.to_s, :width => '100%', :height => '225', class: 'index-img' %>
            <% else %>
            <%= image_tag "/assets/img2.jpeg", :width => '100%', :height => '225', class: 'index-img' %>
            <% end %>
            <div class="like-btn" id="like-btn-<%= product.id %>">
                <%= render 'likes/like', product: product %>
            </div>
        </div>
        <div class="card-body">
            <h5 class="card-title"><%= product.name %></h5>
            <div class="row">
                <div class="ml-2 pl-1">
                    <div class="star-rating mb-2">
                        <div class="star-rating-front" style="width: <%= product.review_score_percentage %>%">★★★★★</div>
                        <div class="star-rating-back">★★★★★</div>
                    </div>
                </div>
                <div class="ml-3">
                    <div class="pt-2">
                        <%= product.reviews.count %>件
                    </div>
                </div>
            </div>
            <div class="d-flex justify-content-between align-items-center">
                <h5 class="card-title mt-3">¥<%= product.price %>(税込み)</h5>
            </div>
                    <h6 class="card-title"><i class="fas fa-store-alt mr-2"></i><%= link_to  "#{product.shop.name}", shop_path(product.shop.id), class: ''%></h6><br>
            <div class="text-right">
                <%= link_to "詳細", product, class: 'btn btn-outline-info w-10' %>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/products/index.html.erb
  <div class="row contents">
      <div class="col-md-3 category-box">
          <div class="card" style="width: 17rem;">
              <div class="card-header">
                  カテゴリー
              </div>
              <ul class="list-group list-group-flush">
                  <% @tags.each do |tag| %>
                  <li class="list-group-item">
                      <%= link_to tag, products_path(tag_name: tag.name) %>
                  </li>
                  <% end %>
              </ul>
          </div>
      </div>

      <div class="col-md-9">
          <div class="album pt-5">
              <div class="row">
                  <%= render partial: 'products/productIndex', locals: { products: @products } %>
              </div>
          </div>
          <div class="bg-white paginate text-center center-block">
          <%= paginate @products %>
          </div>
      </div>
  </div>

app/views/products/new.html.erb
<div class="center-block">
<div class="card">
  <div class="card-header">
    <h3>商品登録</h3>
  </div>
  <div class="card-body mx-auto">
    <%= render partial: 'form', locals: { product: @product } %>
  </div>
</div>
</div>

app/views/products/show.html.erb
<div class="contents mt-4">
<div class="bg-white">
<div class="contents pb-4">
<div class="mb-4 pt-5" style="width: 100%;">
  <div class="row">
    <div class="col-md-6">
       <% if @product.image? %>
        <%= image_tag @product.image.url, :width => '100%', :height => '100%', class: 'show-img'%>
       <% else %>
        <%= image_tag "/assets/img2.jpeg", :width => '100%', :height => '225' ,class: 'show-img'%>
       <% end %>
    </div>
    <div class="col-md-6">
      <div class="card-body">
      <div class="row">
       <div class="col-md-10">
        <h2 class="card-title"><%= @product.name %></h2>
        <h6 class="card-title mt-3"><i class="fas fa-store-alt mr-2"></i><%= link_to  "#{@product.shop.name}", shop_path(@product.shop.id), class: ''%></h6><br>
        </div>
        <div class="col-md-2">
         <div class="like-btn-show mr-4" id="like-btn-<%= @product.id %>">
                <%= render 'likes/like', product: @product %>
         </div>
        </div>
      </div>
        <hr>
        <p class="card-text"><%= simple_format(@product.description) %></p>
        <hr>
        <h2 class="card-title">¥<%= @product.price %></h2>

<div class="col-12 clearfix">
<div class="float-right">


 <%= form_with url: add_item_path, local: true do |f| %>
    <label class="my-1 mr-2" for="inlineFormCustomSelectPref">個数</label>
      <%= f.select :quantity, {'1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '10': 10}, { include_blank: false }, { class: 'custom-select my-1 mr-sm-2 select_tag'} %>
      <% if user_signed_in? %> 
        <%= f.hidden_field :user_id, :value => current_user.id %>
      <% end %>
        <%= f.hidden_field :product_id, :value => @product.id %>
      
     <%= f.submit 'カートに入れる', class: 'btn btn-primary my-1' %> 
  <% end %>

</div>
</div>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'shops/shopInfo', locals: {shop: @product.shop} %>


<section class="section mt-6">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card card-nowrap mb-6" style="white-space: nowrap !important;">
          <header class="card-header">
            <h5 class="card-header-title">
              <%= @product.name %>のレビュー
            </h5>
             <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @product.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @product.avg_score %>点（<%= @product.reviews.count %>件のレビュー）
              </div>
            </div>
          </header>
          <div class="card-content">



<% @reviews.each do |review| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">
        <div class="star-rating mb-2" style="white-space: nowrap !important;">
                <div class="star-rating-front" style="width: <%= review.review_rate_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
        </h5>
        <div class="row no-gutters">
        <div class="col-md-2">
        <p class="card-text"><%= review.user.last_name %></p>
        </div>
        <div class="col-md-10">
        <p class="card-text text-break text-wrap"><%= review.comment %></p>
        </div>
        </div>
      </div>
    </div>
  <% end %>

          </div>
        </div>
        <%= render 'reviews/form', review: @review, product: @product %>
      </div>
    </div>
</section>
</div>
</div>
</div>